### ISSUE TITLE
Task List and To Do:

### ISSUE THREAD

**Issue by OtGW** [DanielK314/DnDSimulator#2]
- [x] organize Archives (not really completed, just checked it as complete so we can test the task list functionality)
- [ ] Add CR sorting to monsters
- [ ] Add Class and Level sorting to Heroes
  - [ ] Add GUI modal pop-up
  - [ ] Autofill functionality based on selections
